USE [master]
GO
/****** Object:  Database [PROG6212_PoE_Part2]    Script Date: 2023/11/29 23:53:19 ******/
CREATE DATABASE [PROG6212_PoE_Part2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PROG6212_PoE_Part2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PROG6212_PoE_Part2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PROG6212_PoE_Part2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PROG6212_PoE_Part2_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PROG6212_PoE_Part2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ARITHABORT OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET RECOVERY FULL 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET  MULTI_USER 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PROG6212_PoE_Part2', N'ON'
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET QUERY_STORE = ON
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PROG6212_PoE_Part2]
GO
/****** Object:  User [NIKKI-PC\tris0]    Script Date: 2023/11/29 23:53:19 ******/
CREATE USER [NIKKI-PC\tris0] FOR LOGIN [NIKKI-PC\tris0] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[AddModulesToSemester]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AddModulesToSemester](
	[AddModulesToSemester_ID] [int] IDENTITY(1,1) NOT NULL,
	[Semester_Name] [nvarchar](255) NOT NULL,
	[Assigned_Modules] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AddModulesToSemester_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Module]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Module](
	[Module_CodeID] [nvarchar](50) NOT NULL,
	[Module_Name] [nvarchar](50) NOT NULL,
	[Number_Of_Credits] [int] NOT NULL,
	[Class_Hours] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Module_CodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RegisterUser]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RegisterUser](
	[Student_Name] [nvarchar](50) NOT NULL,
	[Student_NumberID] [nvarchar](50) NOT NULL,
	[Semester_Name] [nvarchar](255) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Student_NumberID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Semester]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Semester](
	[Semester_NameID] [nvarchar](255) NOT NULL,
	[Start_Date] [date] NOT NULL,
	[Number_Of_Weeks] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Semester_NameID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SemesterModules]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SemesterModules](
	[SemesterModule_ID] [int] IDENTITY(1,1) NOT NULL,
	[Module_Code] [nvarchar](50) NOT NULL,
	[Semester_Name] [nvarchar](255) NOT NULL,
	[Self_Study_Hrs] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SemesterModule_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudentModuleProgress]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudentModuleProgress](
	[Student_NumberID] [nvarchar](50) NOT NULL,
	[Semester_NameID] [varchar](255) NOT NULL,
	[Module_CodeID] [varchar](255) NOT NULL,
	[Self_Study_Hours] [int] NOT NULL,
	[Remaining_HoursID] [int] NOT NULL,
	[Total_Study_Hours] [int] NOT NULL,
	[Date_InsertedID] [datetime] NOT NULL,
 CONSTRAINT [PK__StudentM__0507B590EF9B94B3] PRIMARY KEY CLUSTERED 
(
	[Student_NumberID] ASC,
	[Semester_NameID] ASC,
	[Module_CodeID] ASC,
	[Remaining_HoursID] ASC,
	[Date_InsertedID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudyReminder]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudyReminder](
	[StudyReminderID] [int] IDENTITY(1,1) NOT NULL,
	[SemesterName] [nvarchar](255) NULL,
	[ModuleCode] [nvarchar](50) NULL,
	[ReminderDay] [varchar](255) NULL,
	[StudentNumber] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[StudyReminderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StudySession]    Script Date: 2023/11/29 23:53:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StudySession](
	[Student_NumberID] [nvarchar](50) NOT NULL,
	[Semester_NameID] [varchar](255) NOT NULL,
	[Module_CodeID] [varchar](255) NOT NULL,
	[Allocated_Hours] [varchar](255) NOT NULL,
	[Study_DateID] [date] NOT NULL,
	[Self_Study_Hours] [int] NOT NULL,
	[Hours_Remaining] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Student_NumberID] ASC,
	[Semester_NameID] ASC,
	[Module_CodeID] ASC,
	[Study_DateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[StudentModuleProgress] ADD  CONSTRAINT [DF_StudentModuleProgress_Date_Inserted]  DEFAULT (getdate()) FOR [Date_InsertedID]
GO
ALTER TABLE [dbo].[AddModulesToSemester]  WITH CHECK ADD  CONSTRAINT [Assigned_Modules] FOREIGN KEY([Assigned_Modules])
REFERENCES [dbo].[Module] ([Module_CodeID])
GO
ALTER TABLE [dbo].[AddModulesToSemester] CHECK CONSTRAINT [Assigned_Modules]
GO
ALTER TABLE [dbo].[AddModulesToSemester]  WITH CHECK ADD FOREIGN KEY([Semester_Name])
REFERENCES [dbo].[Semester] ([Semester_NameID])
GO
ALTER TABLE [dbo].[AddModulesToSemester]  WITH CHECK ADD FOREIGN KEY([Semester_Name])
REFERENCES [dbo].[Semester] ([Semester_NameID])
GO
ALTER TABLE [dbo].[RegisterUser]  WITH CHECK ADD FOREIGN KEY([Semester_Name])
REFERENCES [dbo].[Semester] ([Semester_NameID])
GO
ALTER TABLE [dbo].[SemesterModules]  WITH CHECK ADD FOREIGN KEY([Semester_Name])
REFERENCES [dbo].[Semester] ([Semester_NameID])
GO
ALTER TABLE [dbo].[SemesterModules]  WITH CHECK ADD  CONSTRAINT [Module_Code] FOREIGN KEY([Module_Code])
REFERENCES [dbo].[Module] ([Module_CodeID])
GO
ALTER TABLE [dbo].[SemesterModules] CHECK CONSTRAINT [Module_Code]
GO
ALTER TABLE [dbo].[StudyReminder]  WITH CHECK ADD  CONSTRAINT [FK_ModuleCode] FOREIGN KEY([ModuleCode])
REFERENCES [dbo].[Module] ([Module_CodeID])
GO
ALTER TABLE [dbo].[StudyReminder] CHECK CONSTRAINT [FK_ModuleCode]
GO
ALTER TABLE [dbo].[StudyReminder]  WITH CHECK ADD  CONSTRAINT [FK_SemesterName] FOREIGN KEY([SemesterName])
REFERENCES [dbo].[Semester] ([Semester_NameID])
GO
ALTER TABLE [dbo].[StudyReminder] CHECK CONSTRAINT [FK_SemesterName]
GO
ALTER TABLE [dbo].[StudyReminder]  WITH CHECK ADD  CONSTRAINT [FK_StudentNumber] FOREIGN KEY([StudentNumber])
REFERENCES [dbo].[RegisterUser] ([Student_NumberID])
GO
ALTER TABLE [dbo].[StudyReminder] CHECK CONSTRAINT [FK_StudentNumber]
GO
ALTER TABLE [dbo].[StudySession]  WITH CHECK ADD FOREIGN KEY([Student_NumberID])
REFERENCES [dbo].[RegisterUser] ([Student_NumberID])
GO
USE [master]
GO
ALTER DATABASE [PROG6212_PoE_Part2] SET  READ_WRITE 
GO
